name: Repository Events
on: # [push, pull_request, issues]
 push:
    branches:
        - main
        - "feature/*" # matches feature/featA, feature/featB doesn't match feature/featA/featB
        - "feature/**" # matches feature/featA, feature/featB, feature/featA/featB
        - "!feature/featA"
    # branches-ignore:
    #     - develop
    tags:
        - v1.* # match v1.1, v1.1.2
        - '!v1.1.1'
    paths:
        - "**.js"
        - "!app.js"
 pull_request:
    types: [opened, assigned, reopened, synchronize]
    branches:
        - main
    paths:
        - "**.js"
 issues:
    types: [opened]

jobs: 
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3
                