name: Simple Action
on: [workflow_dispatch]

jobs: 
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # - name: Simple JS Action
            #   id: greet 
            #   uses: ./.github/actions/hello
            #   # uses: actions/hello-world-javascript-action@v1
            #   with:
            #     who-to-greet: Atit
            # - name: Log Greeting Time 
            #   run: echo "${{ steps.greet.outputs.time }}"
            # - name: Log ENV Var
            #   run: echo $HELLO_TIME
            - name: Send a joke on Slack
              uses: ./.github/actions/slack-joke
              id: slack-joke
              with:
                slack_username: atit
                upload_joke: true
                slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
            - name: Displaying joke output
              run: echo '${{ steps.slack-joke.outputs.joke }}'