name: Caling Reusable Workflows
on:
    workflow_dispatch:
        inputs:
            name:
                description: Input Description
                type: string
                default: Annie
                required: false 

jobs:
    calling-a-reusable-wf:
        uses: ttteety/workflows/.github/workflows/reusable.yaml@main
        with:
            name: ${{ inputs.name }}
        secrets:
            access-token: ${{ secrets.ACCESS_TOKEN }}